{{- if .Values.config.broomlypro.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "maidsaroundaustin.fullname" . }}-broomlypro
  labels:
    app: {{ template "maidsaroundaustin.name" . }}-broomlypro
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "maidsaroundaustin.name" . }}-broomlypro
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "maidsaroundaustin.name" . }}-broomlypro
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "maidsaroundaustin.fullname" . }}-broomlypro
          image: {{ .Values.images.broomlypro.repository }}:{{ .Values.images.broomlypro.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 2500
          env:
            - name: SITE_URL
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: broomlypro_site_url
            - name: SITE_MODE
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: site_mode
            - name: BROOMLYSQLSERVER_HOST
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: broomlysqlserver_host
            - name: BROOMLYSQLSERVER_USER
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: broomlysqlserver_user
            - name: BROOMLYSQLSERVER_DATABASE
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: broomlysqlserver_database
            - name: BROOMLYSQLSERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: broomlysqlserver_password
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: redis_host
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: redis_password
            - name: FRONTAPP_TOKEN
              valueFrom:
                secretKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: frontapp_token
            - name: FRONTAPP_TEXT_CHANNEL
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: frontapp_text_channel
            - name: FRONTAPP_EMAIL_CHANNEL
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: frontapp_email_channel
            - name: TEST_PHONE
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: test_phone
            - name: TEST_EMAIL
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: test_email
            - name: TEST_NAME
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: test_name
            - name: TEST_DESC
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: test_desc
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
{{- end }}