{{- if .Values.config.broomlycommerce.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "maidsaroundaustin.fullname" . }}-broomlycommerce
  labels:
    app: {{ template "maidsaroundaustin.name" . }}-broomlycommerce
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "maidsaroundaustin.name" . }}-broomlycommerce
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "maidsaroundaustin.name" . }}-broomlycommerce
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "maidsaroundaustin.fullname" . }}-broomlycommerce
          image: {{ .Values.images.broomlycommerce.repository }}:{{ .Values.images.broomlycommerce.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 3500
          env: []
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
{{- end }}