{{- if .Values.config.ecommerce.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "maidsaroundaustin.fullname" . }}-ecommerce
  labels:
    app: {{ template "maidsaroundaustin.name" . }}-ecommerce
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "maidsaroundaustin.name" . }}-ecommerce
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "maidsaroundaustin.name" . }}-ecommerce
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "maidsaroundaustin.fullname" . }}-ecommerce
          image: {{ .Values.images.ecommerce.repository }}:{{ .Values.images.ecommerce.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 2000
          env:
            - name: SITE_URL
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: ecommerce_site_url
            - name: SITE_MODE
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: site_mode
            - name: SITE_HOMEPAGE
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: site_homepage
            - name: SITE_SESSION
              valueFrom:
                secretKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: site_session
            - name: SITE_ZOHO_SOURCE
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: site_zoho_source
            - name: BROOMLYSQLSERVER_HOST
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: broomlysqlserverUser
            - name: BROOMLYSQLSERVER_USER
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: broomlysqlserverUser
            - name: BROOMLYSQLSERVER_DATABASE
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: broomlysqlserverDatabase
            - name: BROOMLYSQLSERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: broomlysqlserverPassword
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: redisHost
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: redisPassword
            - name: FRONTAPP_TOKEN
              valueFrom:
                secretKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: frontappToken
            - name: FRONTAPP_TEXT_CHANNEL
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: frontappTextChannel
            - name: FRONTAPP_EMAIL_CHANNEL
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: frontappEmailChannel
            - name: TEST_PHONE
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: testPhone
            - name: TEST_EMAIL
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: testEmail
            - name: TEST_NAME
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: testName
            - name: TEST_DESC
              valueFrom:
                configMapKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: testDesc
            - name: MAID_STRIPE
              valueFrom:
                secretKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: maidStripe
            - name: YARD_STRIPE
              valueFrom:
                secretKeyRef:
                    name: {{ template "maidsaroundaustin.fullname" . }}
                    key: yardStripe
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
{{- end }}