apiVersion: v1
kind: Secret
metadata:
  name: {{ template "maidsaroundaustin.fullname" . }}
  labels:
    app: {{ template "maidsaroundaustin.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  ecommerce_site_session: {{ .Values.config.ecommerce.siteSession | b64enc }}
  broomlysqlserver_password: {{ .Values.config.broomlysqlserverPassword | b64enc }}
  redis_password: {{ .Values.config.redisPassword | b64enc }}
  brromlyadmin_redis_auth_pass: {{ .Values.config.broomlyadmin.authPass | b64enc }}
  frontapp_token: {{ .Values.config.frontappToken | b64enc }}
  maid_stripe: {{ .Values.config.maidStripe | b64enc }}
  yard_stripe: {{ .Values.config.yardStripe | b64enc }}

